import "./globals.css";


export const metadata = {
  title: "Crud MongoDB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="  h-screen bg-[#fff]">
          {children}
        
        </div>
      </body>
    </html>
  );
}
