import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="  h-screen bg-[#fff]">
          <div className="">{children}</div>
        </div>
      </body>
    </html>
  );
}
