import "./globals.css";
import { SpeedInsights } from '@vercel/speed-insights/next';

export const metadata = {
  title: "Crud MongoDB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="  h-screen bg-[#fff]">
          <div className="">{children}</div>
          <SpeedInsights />
        </div>
      </body>
    </html>
  );
}
